import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="flex items-center justify-between p-4 bg-blue-500 text-white shadow-md">
                    <div>
                        <Link href="/" className="hover:no-underline">
                            <h1 className="text-xl font-bold">Books</h1>
                        </Link>
                    </div>
                    <div className="space-x-4">
                        <Link href="/">Home</Link>
                        <Link href="/form">Form</Link>
                        <Link href="/register">Register</Link>
                        <Link href="/login">Login</Link>
                    </div>
                </header>
                {children}
            </body>
        </html>
    );
}
